- name: Ansible ec2 launch
  hosts: localhost
  connection: local
  gather_facts: False
  tags: provisioning

  vars:
    keypair: mykeypair
    instance_type: t2.micro
    instance_name: test-ec2-instance
    image: ami-04b70fa74e45c3917
    wait: yes
    group: webserver
    region: us-east-1
    security_group: my-instance-security-grp1
    vpc_id: vpc-02d80133cc4d3bbba
    subnet_id: subnet-036d77f40653377b3
  tasks:
    - name: configuring security group for the instance
      ec2_group:
          name: "{{ security_group }}"
          description: my-instance-security_group
          region: "{{ region }}"
          vpc_id: "{{ vpc_id }}"
          rules:
              - proto: tcp
                from_port: 22
                to_port: 22
                cidr_ip: 0.0.0.0/0
              - proto: tcp
                from_port: 80
                to_port: 80
                cidr_ip: 0.0.0.0/0
              - proto: tcp
                from_port: 8080
                to_port: 8080
                cidr_ip: 0.0.0.0/0
          rules_egress:
              - proto: all
                cidr_ip: 0.0.0.0/0
    - name: creating ec2 instance
      ec2_instance:
          security_group: "{{ security_group }}"
          name: "{{ instance_name }}"
          key_name: "{{ keypair }}"
          instance_type: "{{ instance_type}}"
          image_id: "{{ image }}"
          region: "{{ region }}"
          wait: "{{ wait }}"
          vpc_subnet_id: subnet-036d77f40653377b3
          wait_timeout: 3                        