---
- name: Remover instância EC2
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    instance_name: test-ec2-instance
    region: us-east-1
  tasks:
    - name: Obter informações sobre a instância
      ec2_instance_info:
        region: "{{ region }}"
        filters:
          "tag:Name": "{{ instance_name }}"
      register: ec2_info

    - name: Remover a instância
      ec2_instance:
        state: absent
        instance_ids: "{{ item.instance_id }}"
        region: "{{ region }}"
      with_items: "{{ ec2_info.instances }}"